# Generated by Django 3.1.7 on 2021-03-31 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20210331_1639'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.ImageField(default=1, upload_to='images', verbose_name='イメージ画像'),
            preserve_default=False,
        ),
    ]
